### ISSUE TITLE
CDAP STS pods crash when not on default namespace

### ISSUE THREAD

**Issue by kwop** [cdapio/cdap-operator#57]
CDAP operator version : v2.0.2-rc0
CDAP version : 6.3.0
Kubernetes version : 
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.7", GitCommit:"b4455102ef392bf7d594ef96b97a4caa79d729d9", GitTreeState:"clean", BuildDate:"2020-06-17T11:32:20Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

I have harcoded a helm chart -> [cdap.zip](https://github.com/cdapio/cdap-operator/files/5565493/cdap.zip)
when i deploy it from local folder -> helm upgrade --create-namespace --install -n default test ./cdap

- Whenever i deploy a CDAPmaster to a default namespace all pods are usable.
- Whenever i deploy a CDAPmaster to a namespace other than default, the STS pods crashes.

NAME                                |       READY   | STATUS     |        RESTARTS   |AGE|
|----------|----------|----------|----------|----------|
cdap-test-appfabric-0   |                   0/1  |   CrashLoopBackOff  | 7   |       17m|
cdap-test-logs-0          |                 0/1  |   CrashLoopBackOff  | 7   |       17m|
cdap-test-messaging-0    |                  0/1   |  CrashLoopBackOff  | 7    |      17m|
cdap-test-metadata-7b98ffd649-47tp2     |   0/1 |    CrashLoopBackOff  | 7  |        17m|
cdap-test-metrics-0         |               0/1   |  CrashLoopBackOff |  7    |      17m|
cdap-test-preview-0        |                0/1   |  CrashLoopBackOff |  7  |        17m|
cdap-test-router-5fcdc6457c-2vgnv    |      0/1 |    CrashLoopBackOff |  7  |        17m|
cdap-test-runtime-0          |              0/1   |  CrashLoopBackOff  | 7    |      17m|
cdap-test-userinterface-574456c9dd-jkmq9  |  1/1  |   Running   |         0      |    17m|
elasticsearch-master-0      |               1/1  |   Running     |       0     |     17m|
test-hadoop-58665cf7c4-4xmkv     |          1/1 |    Running     |       0   |       17m|
test-postgresql-0             |             1/1    | Running   |         0    |      17m|

`k logs --follow cdap-test-router-5fcdc6457c-2vgnv -n test-namespace`

```
2020-11-19 02:05:46,381 - INFO  [main:i.c.c.m.e.k.AbstractServiceMain@124] - Initializing master service class io.cdap.cdap.master.environment.k8s.RouterServiceMain
2020-11-19 02:05:49,646 - INFO  [main:i.c.c.m.e.k.KubeMasterEnvironment@100] - Initializing Kubernetes environment
2020-11-19 02:05:54,731 - ERROR [main:i.c.c.c.r.DaemonMain@41] - Exception raised when calling init
java.lang.RuntimeException: Exception raised when initializing master environment for k8s
        at io.cdap.cdap.master.environment.k8s.AbstractServiceMain.init(AbstractServiceMain.java:159) [io.cdap.cdap.cdap-app-fabric-6.3.0-SNAPSHOT.jar:na]
        at io.cdap.cdap.common.runtime.DaemonMain.doMain(DaemonMain.java:39) ~[io.cdap.cdap.cdap-common-6.3.0-SNAPSHOT.jar:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_252]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_252]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_252]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_252]
        at io.cdap.cdap.master.environment.k8s.AbstractServiceMain.main(AbstractServiceMain.java:118) [io.cdap.cdap.cdap-app-fabric-6.3.0-SNAPSHOT.jar:na]
        at io.cdap.cdap.master.environment.k8s.RouterServiceMain.main(RouterServiceMain.java:48) [io.cdap.cdap.cdap-master-6.3.0-SNAPSHOT.jar:na]
Caused by: io.kubernetes.client.ApiException: Not Found
        at io.kubernetes.client.ApiClient.handleResponse(ApiClient.java:882) ~[na:na]
        at io.kubernetes.client.ApiClient.execute(ApiClient.java:798) ~[na:na]
        at io.kubernetes.client.apis.CoreV1Api.readNamespacedPodWithHttpInfo(CoreV1Api.java:25009) ~[na:na]
        at io.kubernetes.client.apis.CoreV1Api.readNamespacedPod(CoreV1Api.java:24991) ~[na:na]
        at io.cdap.cdap.master.environment.k8s.KubeMasterEnvironment.getPodInfo(KubeMasterEnvironment.java:218) ~[na:na]
        at io.cdap.cdap.master.environment.k8s.KubeMasterEnvironment.initialize(KubeMasterEnvironment.java:111) ~[na:na]
        at io.cdap.cdap.master.environment.k8s.AbstractServiceMain.init(AbstractServiceMain.java:157) [io.cdap.cdap.cdap-app-fabric-6.3.0-SNAPSHOT.jar:na]
        ... 7 common frames omitted
2020-11-19 02:05:54,818 - ERROR [main:i.c.c.c.r.DaemonMain@45] - Exception raised when calling destroy
java.lang.RuntimeException: Exception raised when initializing master environment for k8s
        at io.cdap.cdap.master.environment.k8s.AbstractServiceMain.init(AbstractServiceMain.java:159) [io.cdap.cdap.cdap-app-fabric-6.3.0-SNAPSHOT.jar:na]
        at io.cdap.cdap.common.runtime.DaemonMain.doMain(DaemonMain.java:39) ~[io.cdap.cdap.cdap-common-6.3.0-SNAPSHOT.jar:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_252]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_252]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_252]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_252]
        at io.cdap.cdap.master.environment.k8s.AbstractServiceMain.main(AbstractServiceMain.java:118) [io.cdap.cdap.cdap-app-fabric-6.3.0-SNAPSHOT.jar:na]
        at io.cdap.cdap.master.environment.k8s.RouterServiceMain.main(RouterServiceMain.java:48) [io.cdap.cdap.cdap-master-6.3.0-SNAPSHOT.jar:na]
Caused by: io.kubernetes.client.ApiException: Not Found
        at io.kubernetes.client.ApiClient.handleResponse(ApiClient.java:882) ~[na:na]
        at io.kubernetes.client.ApiClient.execute(ApiClient.java:798) ~[na:na]
        at io.kubernetes.client.apis.CoreV1Api.readNamespacedPodWithHttpInfo(CoreV1Api.java:25009) ~[na:na]
        at io.kubernetes.client.apis.CoreV1Api.readNamespacedPod(CoreV1Api.java:24991) ~[na:na]
        at io.cdap.cdap.master.environment.k8s.KubeMasterEnvironment.getPodInfo(KubeMasterEnvironment.java:218) ~[na:na]
        at io.cdap.cdap.master.environment.k8s.KubeMasterEnvironment.initialize(KubeMasterEnvironment.java:111) ~[na:na]
        at io.cdap.cdap.master.environment.k8s.AbstractServiceMain.init(AbstractServiceMain.java:157) [io.cdap.cdap.cdap-app-fabric-6.3.0-SNAPSHOT.jar:na]
        ... 7 common frames omitted
```

**Comment by chtyim** [comment]
You need to pass in the namespace via `master.environment.k8s.namespace` in the cdap-site.xml if it is not `default`. Please refer to the source https://github.com/cdapio/cdap/blob/develop/cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java for details.

**Comment by belaz** [comment]
FIXED. 

Thank you @chtyim

**Comment by kwop** [comment]
FIXED.

Thank you @chtyim
