### ISSUE TITLE
java.lang.RuntimeException: java.net.UnknownHostException: reflex-platform-gltest001

### ISSUE THREAD

**Issue by nitinaintahero** [cdapio/cdap-operator#7]
Dear CDAP Team,

I'm running HDP cluster locally:
```
[root@gltest001-mgt-01 samples]# hadoop fs -ls hdfs://reflex-platform-gltest001/
Found 10 items
drwxrwxrwx   - yarn   hadoop          0 2019-06-11 09:47 hdfs://reflex-platform-gltest001/app-logs
drwxr-xr-x   - hdfs   hdfs            0 2019-06-11 09:48 hdfs://reflex-platform-gltest001/apps
drwxr-xr-x   - yarn   hadoop          0 2019-06-11 09:47 hdfs://reflex-platform-gltest001/ats
drwxr-xr-x   - hdfs   hdfs            0 2019-06-11 09:47 hdfs://reflex-platform-gltest001/hdp
drwxr-xr-x   - mapred hdfs            0 2019-06-11 09:47 hdfs://reflex-platform-gltest001/mapred
drwxrwxrwx   - mapred hadoop          0 2019-06-11 09:48 hdfs://reflex-platform-gltest001/mr-history
drwxr-xr-x   - hdfs   hdfs            0 2019-06-11 09:47 hdfs://reflex-platform-gltest001/ranger
drwxrwxrwx   - spark  hadoop          0 2019-06-13 07:19 hdfs://reflex-platform-gltest001/spark2-history
drwxrwxrwx   - hdfs   hdfs            0 2019-06-11 09:48 hdfs://reflex-platform-gltest001/tmp
drwxr-xr-x   - hdfs   hdfs            0 2019-06-11 09:49 hdfs://reflex-platform-gltest001/user
[root@gltest001-mgt-01 samples]#
`````
Now when i deploy cdap_v1alpha1_cdapmaster.yaml, i'm getting ava.net.UnknownHostException: reflex-platform-gltest001.  

````
2019-06-13 07:13:41,322 - INFO  [main:i.c.c.s.d.s.j.DataSourceProvider@155] - Successfully loaded org.postgresql.Driver from /opt/cdap/master/ext/jdbc
2019-06-13 07:13:41,328 - INFO  [main:i.c.c.s.d.s.j.DataSourceProvider@93] - Creating the DataSource with jdbc url: jdbc:postgresql://gltest001-mgt-01.gvs.ggn/postgres?user=postgres&password=postgres
2019-06-13 07:13:41,436 - ERROR [main:o.a.h.f.FileContext@469] - java.net.UnknownHostException: reflex-platform-gltest001
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.cdap.cdap.master.environment.k8s.AbstractServiceMain.main(AbstractServiceMain.java:114)
	at io.cdap.cdap.master.environment.k8s.AppFabricServiceMain.main(AppFabricServiceMain.java:77)
Caused by: com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error in custom provider, java.lang.RuntimeException: java.net.UnknownHostException: reflex-platform-gltest001
  while locating io.cdap.cdap.common.guice.FileContextProvider
  at io.cdap.cdap.common.guice.DFSLocationModule.configure(DFSLocationModule.java:44)
  while locating org.apache.hadoop.fs.FileContext
  while locating io.cdap.cdap.common.guice.DFSLocationModule$LocationFactoryProvider
  at io.cdap.cdap.common.guice.DFSLocationModule.configure(DFSLocationModule.java:45)
  while locating org.apache.twill.filesystem.LocationFactory
    for parameter 2 at io.cdap.cdap.data2.datafabric.dataset.service.executor.DatasetAdminService.<init>(DatasetAdminService.java:69)
  while locating io.cdap.cdap.data2.datafabric.dataset.service.executor.DatasetAdminService
    for parameter 0 at io.cdap.cdap.data2.datafabric.dataset.service.executor.DatasetAdminOpHTTPHandler.<init>(DatasetAdminOpHTTPHandler.java:62)
  while locating io.cdap.cdap.data2.datafabric.dataset.service.executor.DatasetAdminOpHTTPHandler
  while locating io.cdap.http.HttpHandler annotated with @com.google.inject.multibindings.Element(setName=@com.google.inject.name.Named(value=dataset.executor),uniqueId=23, type=MULTIBINDER, keyType=)
  at io.cdap.cdap.data.runtime.DataSetServiceModules$2$1.configure(DataSetServiceModules.java:132) (via modules: io.cdap.cdap.data.runtime.DataSetServiceModules$2 -> io.cdap.cdap.data.runtime.DataSetServiceModules$2$1 -> com.google.inject.multibindings.Multibinder$RealMultibinder)
  while locating java.util.Set<io.cdap.http.HttpHandler> annotated with @com.google.inject.name.Named(value=dataset.executor)
    for parameter 3 at io.cdap.cdap.data2.datafabric.dataset.service.executor.DatasetOpExecutorService.<init>(DatasetOpExecutorService.java:57)
  at io.cdap.cdap.data.runtime.DataSetServiceModules$2$1.configure(DataSetServiceModules.java:137) (via modules: io.cdap.cdap.data.runtime.DataSetServiceModules$2 -> io.cdap.cdap.data.runtime.DataSetServiceModules$2$1)
`````

**Comment by chtyim** [comment]
Where does your kubernetes cluster is running? Was it configured to be able to resolve hostname `reflex-platform-gltest001` via DNS?

**Comment by wyzhang** [comment]
Please reopen if this is still an issue
